# Generated by Django 4.1.7 on 2023-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('street', 'Street'), ('footpath', 'Footpath'), ('washroom', 'washroom')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images'),
        ),
    ]
