# Generated by Django 4.1.7 on 2023-02-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tasks_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-assigned']},
        ),
    ]
