# Generated by Django 4.1.7 on 2023-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_location_alter_tasks_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.DateTimeField(),
        ),
    ]
