# Generated by Django 4.1.7 on 2023-03-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_tasks_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
