# Generated by Django 4.1.7 on 2023-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='approved_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
