# Generated by Django 4.1.7 on 2023-03-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_tasks_approved_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created']},
        ),
    ]
