# Generated by Django 4.1.7 on 2023-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tasks_coins_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
